### ISSUE TITLE
[Question] [mend-examples] Enabling Prioritize scan in Gitlab CI

### ISSUE THREAD

**Issue by midav7** [mend-toolkit/mend-examples#121]
**Question**  
Hi, I'm looking for possibilities to enable Mend Prioritize Scan for our Gitlab integrated projects. I recently came across Gitlab CI example https://github.com/mend-toolkit/mend-examples/blob/main/CI-CD/GitLab/Unified%20Agent/GitLab-cached-ua.yml 
Do I need to add `wss-unified-agent.config` and `-appPath` parameter in order to make `wss-unified-agent.jar` run Prioritize Scan as it described in docs https://docs.mend.io/bundle/sca_user_guide/page/scanning_projects_with_mend_prioritize.html?

**Comment by tabacmend** [comment]
Yes.
Kindly note that we support NodeJS for Prioritize (Backend only): https://docs.mend.io/bundle/sca_user_guide/page/scanning_projects_with_mend_prioritize.html
