### ISSUE TITLE
[FR] [mend-examples] Validating the environment prerequisites for repository integration

### ISSUE THREAD

**Issue by Dima2021** [mend-toolkit/mend-examples#26]
The following validation steps can be added to ensure that the environment prerequisites for repository integration are met:
1. Docker server version 18 and above (docker –version).
2. Ensure all ports required for repository integration are open, specifically all ports used by [docker-compose.yaml](https://github.com/mend-toolkit/mend-examples/blob/main/Repo-Integration/docker-compose.yaml) are open.

The validation steps can be added to [setup.sh](https://github.com/mend-toolkit/mend-examples/blob/main/Repo-Integration/setup.sh) script.

**Comment by tabac-mend** [comment]
In regards to #2:
As the setup.sh and the docker-compose command are creating the containers - the test must run afterward:
From Repo to containers:
curl http://{wss-control}:5678 -> HTTP 404

From Repo to Mend (BB only):
curl https://{customer_mend_instance}/healthCheck -> HTTP 200

From Control/Scanner to Repo:
curl http(s)://{customer_repo}:80/7990/443 -> HTTP 302
